services:
  frontend:
    build:
      context: ./Ace-Books-Frontend
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./Ace-Books-Frontend:/app
    networks:
      - main

  backend:
    build:
      context: ./Ace-Books-Backend
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./Ace-Books-Backend:/app
    networks:
      - main

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - main

  postgres:
    image: postgres:alpine
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data:
    driver: "local"
  pgadmin_data:
    driver: "local"
